config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'products#index'

  get 'profile/:user_id', to: 'users#profile', as: :profile
  post '/:product_id/update', to: 'products#sold', as: :vendido 
  get 'inbox', to: 'users#inbox', as: :inbox 

  resources :products do 
    resources :chats do 
      resources :messages
    end
    resources :comments 
  end
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
 has_many :products
end

app/models/chat.rb
class Chat < ActiveRecord::Base
	belongs_to :buyer,  :class_name => 'User', :foreign_key => ':buyer_id'
	belongs_to :seller,  :class_name => 'User', :foreign_key => ':seller_id'
	belongs_to :product
	has_many :messages
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :product

	def seconds_ago
		(Time.now - self.updated_at)
	end

	def time_ago
		time = Hash.new
		time[:days] = (seconds_ago / 86400).floor
		time[:hours] = ((seconds_ago % 86400) / 3600).floor
		time[:minutes] = (((seconds_ago % 86400) % 3600) / 60).floor
		
		return time 
	end
end

app/models/condition.rb
class Condition < ActiveRecord::Base
	has_many :products
end

app/models/gender.rb
class Gender < ActiveRecord::Base
	has_many :products
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :chat
	belongs_to :user


	def seconds_ago
		(Time.now - self.updated_at)
	end

	def time_ago
		time = Hash.new
		time[:days] = (seconds_ago / 86400).floor
		time[:hours] = ((seconds_ago % 86400) / 3600).floor
		time[:minutes] = (((seconds_ago % 86400) % 3600) / 60).floor
		
		return time 
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
	has_one :category
	has_one :condition
	has_one :gender
	has_many :comments
	has_many :chats

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  before_save { self.email = email.downcase }
  
  has_many :products
  has_many :comments
  has_many :buyers, :class_name => 'Chat', :foreign_key => 'buyer_id'
  has_many :sellers, :class_name => 'Chat', :foreign_key => 'seller_id'
  has_many :messages

  def get_chats
    chats = []
      self.buyers.each do |chat|
        chats.push(chat)
      end
      self.sellers.each do |chat|
        chats.push(chat)
      end

    return (chats.sort_by {|obj| obj.messages.last.created_at}).reverse
  end

  def unread_messages
    if self.get_unread_messages.count != nil
      return self.get_unread_messages.count
    end
  end

  def get_unread_messages
    chats = []
      
      self.buyers.each do |chat|
        if chat.buyer_new == "1"
        chats.push(chat)
        end
      end

      self.sellers.each do |chat|
        if chat.seller_new == "1"
        chats.push(chat)
        end
      end
      return chats
  end

  def products_for_sale
      self.products.where(vendido: "No").count
  end

  def products_sold
    self.products.where(vendido: "Si").count
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

	def new
		@product = Product.find_by(id: params[:product_id])
		@chat = @product.chats.new
		create
	end

	def create
		@product = Product.find_by(id: params[:product_id])
		@chat = @product.chats.new(buyer_id: current_user.id, seller_id: @product.user.id, product_id: @product.id)
		@chat.messages.new(user: current_user, content: "Hola #{@product.user.name.split(" ")[0]}! Me interesa tu producto #{@product.name}")
		if @chat.save
			redirect_to product_chat_path(@product,@chat)
		else
			render :new
		end
	end

	def show
		@product = Product.find_by(id: params[:product_id])
		@chat = Product.find_by(id: params[:product_id]).chats.find_by(id: params[:id])
		@message = Product.find_by(id: params[:product_id]).chats.find_by(id: params[:id]).messages.new
	end
end

app/controllers/genders_controller.rb
class GendersController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_filter :base
  
  def profile
    @user = User.find_by(id: params[:user_id])
    render 'users/profile'
  end
  
  private 
  
  def base

    @products_current_user = Product.where(user_id: current_user)
    @products = Product.all
    @categories = Category.all

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>kloz market</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div>
 <%= render "shared/navbar" %>
</div>
<%= yield %>

</body>
</html>

app/views/shared/_commentform.html.erb
<%= form_for [@product, @comment] do |f| %>
	<div class="row">
		<div class="col-md-12">
			<%= f.hidden_field :user_id, :value => current_user.id %>
			<%= f.text_area :content, :class => 'form-control', size: "100%x3", :placeholder => 'Escribe aquí tu comentario...' %>
		</div>
	</div>
<div class="row">
		<div class="col-md-12 button_addcomment">
			<%= f.submit 'Añadir comentario', :class => 'btn btn-default btn-sm' %>
		</div>
</div>
<% end %>

app/views/shared/_inbox_bar.html.erb
			<div class="panel panel-default structure">
				<div class="panel-heading">
					<h5 class="panel-title text_center">Mensajes</h5>
				</div>
				<div class="panel-body msg_left">
					<br>
					<% current_user.get_chats.each do |chat| %>
					<a class="black" style="display:block" href="/products/<%= chat.product.id %>/chats/<%= chat.id %>">
						<div class="row">
							<div class="col-md-4 no_padding_right">
								<div class="profile-header-container">
									<div class="profile-header-img">
										<img class="img-circle image_chatbox" src="<%= chat.product.image%>"/>
									</div>
								</div>
							</div>
							<div class="col-md-8">
								<b><%= chat.product.name %></b>
								<br>
								<%= chat.product.brand %> | <%= chat.product.price %>€ | Talla: <%= chat.product.size %>
								<br>
								<% if (Condition.find_by(id: chat.product.condition_id).name == "Usado") %>
								<span class="status-chat.product label label-default"><%= Condition.find_by(id: chat.product.condition_id).name %></span>
								<% elsif (Condition.find_by(id: chat.product.condition_id).name == "Nuevo con etiqueta") %>
								<span class="status-chat.product label label-success"><%= Condition.find_by(id: chat.product.condition_id).name %></span>
								<% elsif (Condition.find_by(id: chat.product.condition_id).name == "Nuevo sin etiqueta") %>

								<span class="status-chat.product label label-info"><%= Condition.find_by(id: chat.product.condition_id).name %></span>
								<% end %>
								<br>
								<% if ((chat.buyer_id == current_user.id) && (chat.buyer_new == "1"))  %>
										<span class="status-chat.product label label-danger">¡Mensaje no leído!</span>
										
										<% elsif ((chat.seller_id == current_user.id) && (chat.seller_new == "1")) %>
										<span class="status-chat.product label label-danger">¡Mensaje no leído!</span>
										<% else %>
										<span class="glyphicon glyphicon-time timeago"></span><span class="timeago"> Último mensaje hace
										<% if chat.messages.last.time_ago[:days] == 0 && chat.messages.last.time_ago[:hours] == 0 %>
										<%= chat.messages.last.time_ago[:minutes] %> minutos
										<% elsif chat.messages.last.time_ago[:days] == 0 %>
										<%= chat.messages.last.time_ago[:hours] %> horas
										<% elsif chat.messages.last.time_ago[:days] != 0 %>
										<%= chat.messages.last.time_ago[:days] %> días
										<% end %>
										<% end %>


								
							</span>
						</div>
					</div>
					<hr>
				</a>
				<% end %>
			</div>
		</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-custom">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">klozmarket</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to("Home", products_path)%></li>
        <li><%= link_to("Compra", products_path)%></li>
        <li><%= link_to("Vende", new_product_path) %></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>Hello <%= current_user.name %></li>
              <li><%= link_to 'Perfil', profile_path(current_user) %></li>
              <li><a href="/inbox">Mensajes <span class="badge"><%= current_user.unread_messages %></span></a></li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: 'DELETE' %></li>
            <% else %> 
                <li><%= link_to 'Login', new_user_session_path %></li>
            <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_new_message.html.erb
<%= form_for [@product, @chat, @message] do |f| %>
	<div class="row">
		<div class="col-md-12">
			<%= f.hidden_field :user_id, :value => current_user.id %>
			<%= f.text_area :content, :class => 'form-control', size: "100%x3", :placeholder => 'Escribe aquí tu mensaje...' %>
		</div>
	</div>
<div class="row">
		<div class="col-md-12 button_addcomment">
			<%= f.submit 'Enviar', :class => 'btn btn-default btn-sm' %>
		</div>
</div>
<% end %>