config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'products#index'

  get 'profile/:user_id', to: 'users#profile', as: :profile
  post '/:product_id/update', to: 'products#sold', as: :vendido 
  get 'inbox', to: 'users#inbox', as: :inbox 

  resources :products do 
    resources :chats do 
      resources :messages
    end
    resources :comments 
  end
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
 has_many :products
end

app/models/chat.rb
class Chat < ActiveRecord::Base
	belongs_to :buyer,  :class_name => 'User', :foreign_key => ':buyer_id'
	belongs_to :seller,  :class_name => 'User', :foreign_key => ':seller_id'
	belongs_to :product
	has_many :messages
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :product

	def seconds_ago
		(Time.now - self.updated_at)
	end

	def time_ago
		time = Hash.new
		time[:days] = (seconds_ago / 86400).floor
		time[:hours] = ((seconds_ago % 86400) / 3600).floor
		time[:minutes] = (((seconds_ago % 86400) % 3600) / 60).floor
		
		return time 
	end
end

app/models/condition.rb
class Condition < ActiveRecord::Base
	has_many :products
end

app/models/gender.rb
class Gender < ActiveRecord::Base
	has_many :products
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :chat
	belongs_to :user


	def seconds_ago
		(Time.now - self.updated_at)
	end

	def time_ago
		time = Hash.new
		time[:days] = (seconds_ago / 86400).floor
		time[:hours] = ((seconds_ago % 86400) / 3600).floor
		time[:minutes] = (((seconds_ago % 86400) % 3600) / 60).floor
		
		return time 
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
	has_one :category
	has_one :condition
	has_one :gender
	has_many :comments
	has_many :chats

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  before_save { self.email = email.downcase }
  
  has_many :products
  has_many :comments
  has_many :buyers, :class_name => 'Chat', :foreign_key => 'buyer_id'
  has_many :sellers, :class_name => 'Chat', :foreign_key => 'seller_id'
  has_many :messages

  def get_chats
    chats = []
      self.buyers.each do |chat|
        chats.push(chat)
      end
      self.sellers.each do |chat|
        chats.push(chat)
      end

    return (chats.sort_by {|obj| obj.messages.last.created_at}).reverse
  end

  def unread_messages
    if self.get_unread_messages.count != nil
      return self.get_unread_messages.count
    end
  end

  def get_unread_messages
    chats = []
      
      self.buyers.each do |chat|
        if chat.buyer_new == "1"
        chats.push(chat)
        end
      end

      self.sellers.each do |chat|
        if chat.seller_new == "1"
        chats.push(chat)
        end
      end
      return chats
  end

  def products_for_sale
      self.products.where(vendido: "No").count
  end

  def products_sold
    self.products.where(vendido: "Si").count
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

	def new
		@product = Product.find_by(id: params[:product_id])
		@chat = @product.chats.new
		create
	end

	def create
		@product = Product.find_by(id: params[:product_id])
		@chat = @product.chats.new(buyer_id: current_user.id, seller_id: @product.user.id, product_id: @product.id)
		@chat.messages.new(user: current_user, content: "Hola #{@product.user.name.split(" ")[0]}! Me interesa tu producto #{@product.name}")
		if @chat.save
			redirect_to product_chat_path(@product,@chat)
		else
			render :new
		end
	end

	def show
		@product = Product.find_by(id: params[:product_id])
		@chat = Product.find_by(id: params[:product_id]).chats.find_by(id: params[:id])
		@message = Product.find_by(id: params[:product_id]).chats.find_by(id: params[:id]).messages.new
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@product = Product.find_by(id: params[:product_id])
		@comment = @product.comments.new(content: params[:comment][:content], user_id: params[:comment][:user_id])
		if @comment.save

			redirect_to product_path(Product.find_by(id: params[:product_id]))
		end
	end

	def edit
		@product = Product.find_by(id: params[:product_id])
		@comment = Comment.find_by(id: params[:id])
	end

	def destroy
		@comment = Comment.find(params[:id])
		@id = @comment.product
		@comment.destroy	
		redirect_to product_path(Product.find_by(id: @id))
	end

	def update
		@product = Product.find_by(id: params[:product_id])
		@comment = Comment.find_by(id: params[:id])
		
		if @comment.update(content: params[:comment][:content])
			redirect_to product_path(Product.find_by(id: params[:product_id]))
		end

	end

	private


end

app/controllers/genders_controller.rb
class GendersController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def create

		@chat = Chat.find_by(id: params[:chat_id])
		@product = @chat.product
		@message = @chat.messages.new(user_id: current_user.id, content: params[:message][:content])

		if @message.save
			self.get_new_inbox_receiver(User.find_by(id: @chat.buyer_id), User.find_by(id: @chat.seller_id), @chat)
			redirect_to product_chat_path(@product,@chat)
		else
			render :new
		end
	end

	def get_new_inbox_receiver(buyer, seller, chat)
		if current_user == buyer
			add_unread_message_seller(chat)
		elsif current_user == seller 
			add_unread_message_buyer(chat)
		end
	end

	def add_unread_message_seller(chat)
		chat.seller_new = 1
		chat.save
	end

	def add_unread_message_buyer(chat)
		chat.buyer_new = 1
		chat.save
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
		
	
	def index
		@products = Product.where(vendido: "No")
		@categories = Category.all
	end

	def show
		@product = Product.find_by(id: params[:id])
		@comments = @product.comments.order("Updated_at DESC")
		@comment = Product.find_by(id: params[:id]).comments.new
		@chat = Chat.find_by(buyer_id: current_user, seller_id: @product.user, product_id: @product)
	end

	def new
		@product = Product.new
	end

	def create
		@product = current_user.products.new(price: params[:product][:price], name: params[:product][:name],brand: params[:product][:brand], description: params[:product][:description], image: params[:product][:image], size: params[:product][:size], status: params[:product][:status], category_id: params[:product][:category_id])

		if @product.save
			redirect_to profile_path(current_user)
		else
			render :new
		end
	end

	def destroy
		@product = Product.find(params[:id])

		if @product.destroy	
			redirect_to profile_path(current_user)
		end
	end

	def sold
		@product = Product.find_by(id: params[:product_id])
		@product.vendido = "Si"
		@product.save

		redirect_to profile_path(current_user)
	end

	private

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_filter :base
  
  def profile
    @user = User.find_by(id: params[:user_id])
    render 'users/profile'
  end
  
  private 
  
  def base

    @products_current_user = Product.where(user_id: current_user)
    @products = Product.all
    @categories = Category.all

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/show.html.erb
<% if current_user.id == @chat.buyer_id %>
<% @chat.buyer_new = 0 %>
<% @chat.save %>
<% elsif current_user.id == @chat.seller_id %>
<% @chat.seller_new = 0 %>
<% @chat.save %>
<% end %>
<div class="container-fluid structure">
	<div class="row structure">
		<div class="col-md-3 structure">
<%= render "shared/inbox_bar" %>
	</div>
	<div class="col-md-6 structure">
		<div class="well">
			<div class="row">
				<div class="col-md-2">
					<div class="profile-header-container">
						<div class="profile-header-img">
							<img class="img-circle" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" />
							<div class="rank-label-container">
								<span class="label label-default rank-label">3.5 <span class="glyphicon glyphicon-star" aria-hidden="true"></span></span>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-5">
					<% if current_user.id == @chat.seller_id %>
					<%= User.find_by(id: @chat.buyer_id).name %>
					<% elsif current_user.id == @chat.buyer_id %>
					<%= User.find_by(id: @chat.seller_id).name %>
					<% end %>
				</div>
			</div>
			<hr data-brackets-id="12673">
			<ul data-brackets-id="12674" id="sortable" class="list-unstyled ui-sortable chatbox">
				<% if @chat.messages != nil %>
				<% @chat.messages.each do |message| %>
				<div class="row">
					<% if message.user == current_user %>
					<div class="col-md-12">
						<small class="pull-right text-muted chat_format">
						<span class="glyphicon glyphicon-time"></span> hace
						<% if message.time_ago[:days] == 0 && message.time_ago[:hours] == 0 %>
						<%= message.time_ago[:minutes] %> minutos
						<% elsif message.time_ago[:days] == 0 %>
						<%= message.time_ago[:hours] %> horas
						<% elsif message.time_ago[:days] != 0 %>
						<%= message.time_ago[:days] %> días
						<% end %>
						</small>
						<li class="pull-right chat_me chat_format structure_width"><%= message.content %></li>
					</div>
					<% else %>
					<div class="col-md-12">
						<small class="pull-left text-muted chat_format">
						<span class="glyphicon glyphicon-time"></span> hace
						<% if message.time_ago[:days] == 0 && message.time_ago[:hours] == 0 %>
						<%= message.time_ago[:minutes] %> minutos
						<% elsif message.time_ago[:days] == 0 %>
						<%= message.time_ago[:hours] %> horas
						<% elsif message.time_ago[:days] != 0 %>
						<%= message.time_ago[:days] %> días
						<% end %>
						</small>
						<li class="pull-left chat_other chat_format structure_width"><%= message.content %></li>
					</div>
					<% end %>
				</div>
				<% end %>
				<% end %>
			</ul>
			<div class="input-group">
				<%= render "shared/new_message" %>
			</div>
		</div>
	</div>
					<div class="col-md-3">
						<div class="panel panel-default">
							<div class="panel-body">
								<% if (@product.user == current_user) && (@product.vendido == "No") %>
								<%= link_to raw("<i class=\"glyphicon glyphicon-remove\"></i>"), product_path(@product), :data => { :confirm => '¿Estás seguro de que quieres eliminar el producto?' }, :class=> "cross_to_delete", method: :delete %>
								<% end %>
								<div class="image_box">
									<img class="img-responsive" src="<%= @product.image %>" alt="<%= @product.name %> (<%= @product.brand %>)" data-toggle="modal" data-target="#myModal">
								</div>
								<% if @product.vendido == "Si" %>
								<br>
								<div class="row">
									<div class="col-md-5 text_right no_padding_right">
										<span class="glyphicon glyphicon-ok-sign sold_icon" aria-hidden="true"></span>
									</div>
									<div class="col-md-7 text_left sold_text_icon">
										VENDIDO
									</div>
								</div>
								
								
								<% end %>
								<div class="text_center description_field">
									<% if (Condition.find_by(id: @product.condition_id).name) == "Usado" %>
									<span class="status-product label label-default"><%= Condition.find_by(id: @product.condition_id).name %></span>
									<% elsif (Condition.find_by(id: @product.condition_id).name) == "Nuevo con etiqueta" %>
									<span class="status-product label label-success"><%= Condition.find_by(id: @product.condition_id).name %></span>
									<% elsif (Condition.find_by(id: @product.condition_id).name) == "Nuevo sin etiqueta" %>
									<span class="status-product label label-info"><%= Condition.find_by(id: @product.condition_id).name %></span>
									<% end %>
								</div>
								<div class="text_center">
									<b><%= @product.brand %></b> | Talla: <b><%= @product.size %></b>
								</div>
								<div class="margin_bottom text_center">
									<% if (@product.user == current_user) %>
									<div class="row">
										<% unless (@product.vendido == "Si") %>
										
										<div class="col-md-6 no_padding_right">
											<%= button_to "¡Vendido!",vendido_path(@product), :data => { :confirm => '¿Has vendido realmente el producto?' }, :class=> "boton btn btn-success btn-md", method: :post %>
										</div>
										<div class="col-md-6 no_padding_left">
											<%= button_to "#{@product.price}€",product_path(@product), :class=> "boton btn btn-success btn-outline text_bold", method: :get %>
										</div>
										<% end %>
											<div class="col-md-12">
											<%= button_to "Ver detalle",product_path(@product), :class=> "boton btn btn-warning btn-md margin", method: :get %>
											</div>
									</div>
									<% elsif (@product.user != current_user) && (@product.vendido == "No") %>
									<div class="row">
										<div class="col-md-6 no_padding_right">
											<%= button_to "Ver más",product_path(@product), :class=> "boton btn btn-warning btn-outline text_bold", method: :get %>
										</div>
										<div class="col-md-6 no_padding_left">
											<% if (Chat.find_by(buyer_id: current_user.id, seller_id: @product.user.id, product_id: @product)) %>
											<%= button_to "#{@product.price}€",product_chat_path(@product, (Chat.find_by(buyer_id: current_user, seller_id: @product.user, product_id: @product))), :class=> "boton btn btn-success btn-outline text_bold", method: :get %>
											<% else %>
											<%= button_to "#{@product.price}€",new_product_chat_path(@product), :class=> "boton btn btn-success btn-outline text_bold", method: :get %>
											<% end %>
										</div>
									</div>
									<% end %>
								</div>
							</div>
						</div>

	</div>
</div>
</div>

<script>
$( "ul.chatbox" ).scrollTop( 30000 );
</script>

app/views/comments/edit.html.erb
<%= form_for [@product, @comment] do |f| %>
<%= f.text_area :content, :class => 'form-control', size: "100%x3" %>
<%= f.submit 'Update ', :class => 'btn btn-info btn-xs' %>
<% end %>

app/views/products/index.html.erb
<div class="most-active">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default ">
					<div class="panel-body">
				<ul class="nav nav-pills">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Género<span class="caret"></span></a>
						<ul class="dropdown-menu">
							<% @categories.each do |category| %>
							<li><%= link_to(category.name, category_path(category))%></li>
							<% end %>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categorías<span class="caret"></span></a>
						<ul class="dropdown-menu">
							<% @categories.each do |category| %>
							<li><%= link_to(category.name, category_path(category))%></li>
							<% end %>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Uso<span class="caret"></span></a>
						<ul class="dropdown-menu">
							<% @categories.each do |category| %>
							<li><%= link_to(category.name, category_path(category))%></li>
							<% end %>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Precio<span class="caret"></span></a>
						<ul class="dropdown-menu">
							<% @categories.each do |category| %>
							<li><%= link_to(category.name, category_path(category))%></li>
							<% end %>
						</ul>
					</li>
				</ul>
			</div>
			</div>
			</div>
		</div>
		<div class="row">
			<% @products.each do |product| %>
			<div class="col-md-2">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="image_box">
							<img class="img-responsive" src="<%= product.image %>" alt="<%= product.name %> (<%= product.brand %>)" data-toggle="modal" data-target="#myModal">
						</div>
						<div class="text_center description_field">
							<% if Condition.find_by(id: product.condition_id).name == "Usado" %>
							<span class="status-product label label-default"><%= Condition.find_by(id: product.condition_id).name %></span>
							<% elsif Condition.find_by(id: product.condition_id).name == "Nuevo con etiqueta" %>
							<span class="status-product label label-success"><%= Condition.find_by(id: product.condition_id).name %></span>
							<% elsif Condition.find_by(id: product.condition_id).name == "Nuevo sin etiqueta" %>
							<span class="status-product label label-info"><%= Condition.find_by(id: product.condition_id).name %></span>
							<% end %>
						</div>
						<div class="text_center">
							<b><%= product.brand %></b> | Talla: <b><%= product.size %></b>
						</div>
						<div class="margin_bottom">
							<div class="row">
								<div class="col-md-6 no_padding_right">
									<%= button_to "Ver más",product_path(product), :class=> "boton btn btn-warning btn-outline text_bold", method: :get %>
								</div>
								<div class="col-md-6 no_padding_left">
									<% if (product.user != current_user) && (product.vendido == "No") %>
										<% if (Chat.find_by(buyer_id: current_user.id, seller_id: product.user.id, product_id: product)) %>
										<%= button_to "#{product.price}€",product_chat_path(product, (Chat.find_by(buyer_id: current_user, seller_id: product.user, product_id: product))), :class=> "boton btn btn-success btn-outline text_bold", method: :get %>
										<% else %>
										<%= button_to "#{product.price}€",new_product_chat_path(product), :class=> "boton btn btn-success btn-outline text_bold", method: :get %>
										<% end %>
										<% end %>
								</div>
							</div>
							
							
						</div>
					</div>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="myModalLabel">Im the awesome cat!</h4>
			</div>
			<div class="modal-body">
				<img class="img-responsive" src="http://lorempixel.com/600/400/cats/?42" alt="The awesome description">
			</div>
		</div>
	</div>
</div>
</div>
<script>
	
$(".image_box img").click(function(event) {
var src = ($(event.target).attr("src"))
var alt = ($(event.target).attr("alt"))
$(".modal-body img").attr("src",src)
$(".modal-body img").attr("alt",alt)
$("#myModalLabel").text(alt)
});
</script>

app/views/products/new.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h5 class="panel-title text_center">Poner producto a la venta</h5>
				</div>
				
				<div class="panel panel-body form_fitting">
					<%= form_for @product do |f| %>
					<div class="row">
						<div class="col-md-6">
							
							<%= f.label "Nombre" %>
							<%= f.text_field :name, :class => 'form-control', :placeholder => 'Ejemplo: "Camiseta de cuadros". NO incluyas la marca' %>
							<br>
							<%= f.label "Marca" %>
							<%= f.text_field :brand, :class => 'form-control', :placeholder => 'Ejemplo: "Zara"' %>
							<br>
							<%= f.label "Precio" %>
							<%= f.number_field :price, max: 10000, min:0.01, step: 0.01, :class => 'form-control', :placeholder => 'Ejemplo: "12,50"' %>
							<br>
							<%= f.label "Talla" %>
							<%= f.text_field :size, :class => 'form-control', :placeholder => 'Ejemplo: "S"' %>
							<br>
							<%= f.label "Género" %>
							<%= f.collection_select :condition, Gender.all.collect,  :id, :name, {include_blank: "Elige un género"}, :class => 'form-control' %>
							<br>
							<%= f.label "Categoría" %>
							<%= f.collection_select :category_id, Category.all.collect,  :id, :name, {include_blank: "Elige una categoría"}, :class => 'form-control' %>
							<br>
							<%= f.label "Estado del producto" %>
							<%= f.collection_select :condition, Condition.all.collect,  :id, :name, {include_blank: "Elige un estado"}, :class => 'form-control' %>
							<br>
						</div>
						<div class="col-md-6">
							<%= f.label "Descripción" %>
							<%= f.text_area :description, :class => 'form-control', :placeholder => 'Ejemplo: "Edición especial para el verano pasado, comprada en rebajas."' %>
							<br>
							<%= f.label "Imagen" %>
							<%= f.file_field :image , :class => 'form-control' %>
						</div>
					<div class="row">
						<div class="col-md-12 button_addcomment">
							<%= f.submit 'Publicar producto', :class => 'btn btn-default btn-sm' %>
						</div>
						</div>
					
					</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/inbox.html.erb
<div class="container-fluid structure">
	<div class="row structure">
		<div class="col-md-3 structure">
<%= render "shared/inbox_bar" %>
	</div>

app/views/users/profile.html.erb
<div class="most-active">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h5 class="panel-title text_center">Perfil</h5>
					</div>
					<div class="row">
						<div class="col-md-6 col-md-offset-3">
							<div class="panel-body">
								<div class="profile_space">
									<div class="profile-header-container">
										<div class="profile-header-img">
											<img class="img-circle" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" />
											<div class="rank-label-container">
												<span class="label label-default rank-label">3.5 <span class="glyphicon glyphicon-star" aria-hidden="true"></span></span>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="text_center description_field kloz_color">
								<%= link_to "#{@user.name}", profile_path(@user) %>
							</div>
							<div class="text_center">
								<p>
									Productos en venta : <%= @user.products_for_sale %>
								</p>
								<p>
									Productos vendidos : <%= @user.products_sold %>
								</p>
							</div>
							
						</div>
					</div>
				</div>
			</div>
			
			<div class="col-md-8">
				<div class="row">
					<% @user.products.each do |product| %>
					<div class="col-md-3">
						<div class="panel panel-default">
							<div class="panel-body">
								<% if (product.user == current_user) && (product.vendido == "No") %>
								<%= link_to raw("<i class=\"glyphicon glyphicon-remove\"></i>"), product_path(product), :data => { :confirm => '¿Estás seguro de que quieres eliminar el producto?' }, :class=> "cross_to_delete", method: :delete %>
								<% end %>
								<div class="image_box">
									<img class="img-responsive" src="<%= product.image %>" alt="<%= product.name %> (<%= product.brand %>)" data-toggle="modal" data-target="#myModal">
								</div>
								<% if product.vendido == "Si" %>
								<br>
								<div class="row">
									<div class="col-md-5 text_right no_padding_right">
										<span class="glyphicon glyphicon-ok-sign sold_icon" aria-hidden="true"></span>
									</div>
									<div class="col-md-7 text_left sold_text_icon">
										VENDIDO
									</div>
								</div>
								
								
								<% end %>
								<div class="text_center description_field">
									<% if (Condition.find_by(id: product.condition_id).name == "Usado") %>
									<span class="status-product label label-default"><%= Condition.find_by(id: product.condition_id).name %></span>
									<% elsif (Condition.find_by(id: product.condition_id).name) == "Nuevo con etiqueta" %>
									<span class="status-product label label-success"><%= Condition.find_by(id: product.condition_id).name %></span>
									<% elsif (Condition.find_by(id: product.condition_id).name) == "Nuevo sin etiqueta" %>
									<span class="status-product label label-info"><%= Condition.find_by(id: product.condition_id).name %></span>
									<% end %>
								</div>
								<div class="text_center">
									<b><%= product.brand %></b> | Talla: <b><%= product.size %></b>
								</div>
								<div class="margin_bottom text_center">
									<% if (product.user == current_user) %>
									<div class="row">
										<% unless (product.vendido == "Si") %>
										
										<div class="col-md-6 no_padding_right">
											<%= button_to "¡Vendido!",vendido_path(product), :data => { :confirm => '¿Has vendido realmente el producto?' }, :class=> "boton btn btn-success btn-md", method: :post %>
										</div>
										<div class="col-md-6 no_padding_left">
											<%= button_to "#{product.price}€",product_path(product), :class=> "boton btn btn-success btn-outline text_bold", method: :get %>
										</div>
										<% end %>
											<div class="col-md-12">
											<%= button_to "Ver detalle",product_path(product), :class=> "boton btn btn-warning btn-md margin", method: :get %>
											</div>
									</div>
									<% elsif (product.user != current_user) && (product.vendido == "No") %>
									<div class="row">
										<div class="col-md-6 no_padding_right">
											<%= button_to "Ver más",product_path(product), :class=> "boton btn btn-warning btn-outline text_bold", method: :get %>
										</div>
										<div class="col-md-6 no_padding_left">
											<% if (Chat.find_by(buyer_id: current_user.id, seller_id: product.user.id, product_id: product)) %>
											<%= button_to "#{product.price}€",product_chat_path(product, (Chat.find_by(buyer_id: current_user, seller_id: product.user, product_id: product))), :class=> "boton btn btn-success btn-outline text_bold", method: :get %>
											<% else %>
											<%= button_to "#{product.price}€",new_product_chat_path(product), :class=> "boton btn btn-success btn-outline text_bold", method: :get %>
											<% end %>
										</div>
									</div>
									<% end %>
								</div>
							</div>
						</div>
					</div>
					<% end %>
					
				</div>
			</div>
		</div>
	</div>
</div>